### ISSUE TITLE
ReferenceError: curry$ is not defined

### ISSUE THREAD

**Issue by willin** [gkz/prelude-ls#111]
https://github.com/gkz/prelude-ls/blob/master/src/Func.ls#L5

```ls
curry = (f) ->
  curry$ f # using util method curry$ from livescript

a = curry 123
console.log a
```

```
Failed at: src/index.ls
ReferenceError: curry$ is not defined
    at curry (/Users/willin/Desktop/lsdemo/src/index.ls:4:3)
1| // Generated by LiveScript 1.5.0
2| var curry, a;
3| curry = function(f){
4+   return curry$(f);
5| };
6| a = curry(123);
7| console.log(a);
8|
    at Object.<anonymous> (/Users/willin/Desktop/lsdemo/src/index.ls:6:5)
 2| var curry, a;
 3| curry = function(f){
 4|   return curry$(f);
 5| };
 6+ a = curry(123);
 7| console.log(a);
 8|
 9|
10|
    at Module._compile (module.js:573:30)
    at Object.LiveScript.run (/Users/willin/Desktop/lsdemo/node_modules/livescript/lib/node.js:31:19)
    at compileScript (/Users/willin/Desktop/lsdemo/node_modules/livescript/lib/command.js:222:31)
    at /Users/willin/Desktop/lsdemo/node_modules/livescript/lib/command.js:152:11
    at /Users/willin/Desktop/lsdemo/node_modules/livescript/lib/command.js:142:7
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:504:3)
```

**Comment by anko** [comment]
Could you share more precise steps to reproduce the issue?

I tried this, and got no errors:
```
$ cd $(mktemp -d)
$ npm i livescript prelude-ls
[ ... ]
$ echo "a = (require \\prelude-ls).curry (+); console.log a 1 ; console.log a 1 2" \
    | lsc
[Function]
3

```

**Comment by vendethiel** [comment]
That's just because you tried to copy-paste the definition, not using the package.

The way `curry` works here is that it relies on the fact some other function in the file uses LiveScript's curried functions (`-->` or `~~>`).

**Comment by tcrowe** [comment]
I think when the *.ls is compiled and needs currying this will get appended:
https://github.com/gkz/prelude-ls/blob/master/lib/Func.js#L53

**Comment by gkz** [comment]
Yeah we are super hacking this here, and depending on the fact that the "curry$" function will be available (rather than redefining it)
